// <auto-generated />
using System;
using FraudDetection.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FraudDetection.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802133953_AddAlertAmount")]
    partial class AddAlertAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fraud_backend")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FraudDetection.Infrastructure.Persistence.Records.AlertRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_id");

                    b.Property<decimal>("AmountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<string>("FraudType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fraud_type");

                    b.Property<double?>("GnnScore")
                        .HasColumnType("double precision")
                        .HasColumnName("gnn_score");

                    b.Property<double?>("IsolationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("isolation_score");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_note");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reviewed_by");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<double?>("TftScore")
                        .HasColumnType("double precision")
                        .HasColumnName("tft_score");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<double?>("XgboostScore")
                        .HasColumnType("double precision")
                        .HasColumnName("xgboost_score");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_alert_id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_transaction_id");

                    b.HasIndex("Operator", "Status", "CreatedAt")
                        .HasDatabaseName("ix_alerts_operator_status_created_at");

                    b.ToTable("alerts", "fraud_backend");
                });

            modelBuilder.Entity("FraudDetection.Infrastructure.Persistence.Records.PendingTransactionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<bool>("BeneficiaryIsMerchant")
                        .HasColumnType("boolean")
                        .HasColumnName("beneficiary_is_merchant");

                    b.Property<string>("BeneficiaryToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("beneficiary_token");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("ClientToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_token");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enqueued_at");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_at");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator");

                    b.Property<bool>("SimChanged72h")
                        .HasColumnType("boolean")
                        .HasColumnName("sim_changed72h");

                    b.Property<DateTime?>("SimChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sim_changed_at");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<bool>("UssdSession")
                        .HasColumnType("boolean")
                        .HasColumnName("ussd_session");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone");

                    b.HasKey("Id")
                        .HasName("pk_pending_transactions");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ix_pending_transactions_transaction_id");

                    b.HasIndex("Operator", "EnqueuedAt")
                        .HasDatabaseName("ix_pending_transactions_operator_enqueued_at");

                    b.ToTable("pending_transactions", "fraud_backend");
                });

            modelBuilder.Entity("FraudDetection.Infrastructure.Persistence.Records.StrReportRecord", b =>
                {
                    b.Property<string>("ReportId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("report_id");

                    b.Property<string>("AgentNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("agent_note");

                    b.Property<string>("AlertId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_id");

                    b.Property<string>("ConfirmedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("confirmed_by");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<string>("FraudType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fraud_type");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<double?>("GnnScore")
                        .HasColumnType("double precision")
                        .HasColumnName("gnn_score");

                    b.Property<double?>("IsolationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("isolation_score");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<double?>("TftScore")
                        .HasColumnType("double precision")
                        .HasColumnName("tft_score");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<bool>("Transmitted")
                        .HasColumnType("boolean")
                        .HasColumnName("transmitted");

                    b.Property<DateTime?>("TransmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transmitted_at");

                    b.Property<double?>("XgboostScore")
                        .HasColumnType("double precision")
                        .HasColumnName("xgboost_score");

                    b.HasKey("ReportId")
                        .HasName("pk_str_reports");

                    b.HasIndex("AlertId")
                        .IsUnique()
                        .HasDatabaseName("ix_str_reports_alert_id");

                    b.HasIndex("Operator", "GeneratedAt")
                        .HasDatabaseName("ix_str_reports_operator_generated_at");

                    b.HasIndex("Operator", "Transmitted")
                        .HasDatabaseName("ix_str_reports_operator_transmitted");

                    b.ToTable("str_reports", "fraud_backend");
                });

            modelBuilder.Entity("FraudDetection.Infrastructure.Persistence.Records.TransactionRecord", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_id");

                    b.Property<string>("AgentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_id");

                    b.Property<string>("AlertId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<bool>("BeneficiaryIsMerchant")
                        .HasColumnType("boolean")
                        .HasColumnName("beneficiary_is_merchant");

                    b.Property<string>("BeneficiaryToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("beneficiary_token");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("ClientToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("client_token");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Decision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("device_id");

                    b.Property<string>("FraudType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fraud_type");

                    b.Property<double?>("GnnScore")
                        .HasColumnType("double precision")
                        .HasColumnName("gnn_score");

                    b.Property<double?>("InferenceTimeMs")
                        .HasColumnType("double precision")
                        .HasColumnName("inference_time_ms");

                    b.Property<bool>("IsDefaultReview")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default_review");

                    b.Property<double?>("IsolationScore")
                        .HasColumnType("double precision")
                        .HasColumnName("isolation_score");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_version");

                    b.Property<string>("NotificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("notification_status");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operator");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at");

                    b.Property<bool>("SimChanged72h")
                        .HasColumnType("boolean")
                        .HasColumnName("sim_changed72h");

                    b.Property<DateTime?>("SimChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sim_changed_at");

                    b.Property<double?>("TftScore")
                        .HasColumnType("double precision")
                        .HasColumnName("tft_score");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<bool>("UssdSession")
                        .HasColumnType("boolean")
                        .HasColumnName("ussd_session");

                    b.Property<double?>("XgboostScore")
                        .HasColumnType("double precision")
                        .HasColumnName("xgboost_score");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zone");

                    b.HasKey("TransactionId")
                        .HasName("pk_transactions");

                    b.HasIndex("Operator", "Decision")
                        .HasDatabaseName("ix_transactions_operator_decision");

                    b.HasIndex("Operator", "NotificationStatus")
                        .HasDatabaseName("ix_transactions_operator_notification_status");

                    b.HasIndex("Operator", "ReceivedAt")
                        .HasDatabaseName("ix_transactions_operator_received_at");

                    b.ToTable("transactions", "fraud_backend");
                });
#pragma warning restore 612, 618
        }
    }
}
